# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/naif/programmes/clion-2018.1.5/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/naif/programmes/clion-2018.1.5/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/naif/Documents/squeezeCNN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/naif/Documents/squeezeCNN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/naif/programmes/clion-2018.1.5/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/naif/programmes/clion-2018.1.5/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/naif/Documents/squeezeCNN/CMakeFiles /home/naif/Documents/squeezeCNN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/naif/Documents/squeezeCNN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named squeezecnn

# Build rule for target.
squeezecnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 squeezecnn
.PHONY : squeezecnn

# fast build rule for target.
squeezecnn/fast:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/build
.PHONY : squeezecnn/fast

src/base64.o: src/base64.cpp.o

.PHONY : src/base64.o

# target to build an object file
src/base64.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/base64.cpp.o
.PHONY : src/base64.cpp.o

src/base64.i: src/base64.cpp.i

.PHONY : src/base64.i

# target to preprocess a source file
src/base64.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/base64.cpp.i
.PHONY : src/base64.cpp.i

src/base64.s: src/base64.cpp.s

.PHONY : src/base64.s

# target to generate assembly for a file
src/base64.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/base64.cpp.s
.PHONY : src/base64.cpp.s

src/face_extraction.o: src/face_extraction.cpp.o

.PHONY : src/face_extraction.o

# target to build an object file
src/face_extraction.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/face_extraction.cpp.o
.PHONY : src/face_extraction.cpp.o

src/face_extraction.i: src/face_extraction.cpp.i

.PHONY : src/face_extraction.i

# target to preprocess a source file
src/face_extraction.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/face_extraction.cpp.i
.PHONY : src/face_extraction.cpp.i

src/face_extraction.s: src/face_extraction.cpp.s

.PHONY : src/face_extraction.s

# target to generate assembly for a file
src/face_extraction.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/face_extraction.cpp.s
.PHONY : src/face_extraction.cpp.s

src/face_tracking.o: src/face_tracking.cpp.o

.PHONY : src/face_tracking.o

# target to build an object file
src/face_tracking.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/face_tracking.cpp.o
.PHONY : src/face_tracking.cpp.o

src/face_tracking.i: src/face_tracking.cpp.i

.PHONY : src/face_tracking.i

# target to preprocess a source file
src/face_tracking.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/face_tracking.cpp.i
.PHONY : src/face_tracking.cpp.i

src/face_tracking.s: src/face_tracking.cpp.s

.PHONY : src/face_tracking.s

# target to generate assembly for a file
src/face_tracking.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/face_tracking.cpp.s
.PHONY : src/face_tracking.cpp.s

src/mainAlgo.o: src/mainAlgo.cpp.o

.PHONY : src/mainAlgo.o

# target to build an object file
src/mainAlgo.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/mainAlgo.cpp.o
.PHONY : src/mainAlgo.cpp.o

src/mainAlgo.i: src/mainAlgo.cpp.i

.PHONY : src/mainAlgo.i

# target to preprocess a source file
src/mainAlgo.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/mainAlgo.cpp.i
.PHONY : src/mainAlgo.cpp.i

src/mainAlgo.s: src/mainAlgo.cpp.s

.PHONY : src/mainAlgo.s

# target to generate assembly for a file
src/mainAlgo.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/mainAlgo.cpp.s
.PHONY : src/mainAlgo.cpp.s

src/network_utils.o: src/network_utils.cpp.o

.PHONY : src/network_utils.o

# target to build an object file
src/network_utils.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/network_utils.cpp.o
.PHONY : src/network_utils.cpp.o

src/network_utils.i: src/network_utils.cpp.i

.PHONY : src/network_utils.i

# target to preprocess a source file
src/network_utils.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/network_utils.cpp.i
.PHONY : src/network_utils.cpp.i

src/network_utils.s: src/network_utils.cpp.s

.PHONY : src/network_utils.s

# target to generate assembly for a file
src/network_utils.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/network_utils.cpp.s
.PHONY : src/network_utils.cpp.s

src/training_generator.o: src/training_generator.cpp.o

.PHONY : src/training_generator.o

# target to build an object file
src/training_generator.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/training_generator.cpp.o
.PHONY : src/training_generator.cpp.o

src/training_generator.i: src/training_generator.cpp.i

.PHONY : src/training_generator.i

# target to preprocess a source file
src/training_generator.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/training_generator.cpp.i
.PHONY : src/training_generator.cpp.i

src/training_generator.s: src/training_generator.cpp.s

.PHONY : src/training_generator.s

# target to generate assembly for a file
src/training_generator.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/training_generator.cpp.s
.PHONY : src/training_generator.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/video_consumer.o: src/video_consumer.cpp.o

.PHONY : src/video_consumer.o

# target to build an object file
src/video_consumer.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/video_consumer.cpp.o
.PHONY : src/video_consumer.cpp.o

src/video_consumer.i: src/video_consumer.cpp.i

.PHONY : src/video_consumer.i

# target to preprocess a source file
src/video_consumer.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/video_consumer.cpp.i
.PHONY : src/video_consumer.cpp.i

src/video_consumer.s: src/video_consumer.cpp.s

.PHONY : src/video_consumer.s

# target to generate assembly for a file
src/video_consumer.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/src/video_consumer.cpp.s
.PHONY : src/video_consumer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... squeezecnn"
	@echo "... src/base64.o"
	@echo "... src/base64.i"
	@echo "... src/base64.s"
	@echo "... src/face_extraction.o"
	@echo "... src/face_extraction.i"
	@echo "... src/face_extraction.s"
	@echo "... src/face_tracking.o"
	@echo "... src/face_tracking.i"
	@echo "... src/face_tracking.s"
	@echo "... src/mainAlgo.o"
	@echo "... src/mainAlgo.i"
	@echo "... src/mainAlgo.s"
	@echo "... src/network_utils.o"
	@echo "... src/network_utils.i"
	@echo "... src/network_utils.s"
	@echo "... src/training_generator.o"
	@echo "... src/training_generator.i"
	@echo "... src/training_generator.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/video_consumer.o"
	@echo "... src/video_consumer.i"
	@echo "... src/video_consumer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

